module.exports = [
    {
        name: 1,
        code: '#ed6103'
    }, {
        name: 2,
        code: '#ffab00'
    }, {
        name: 3,
        code: '#ebebeb'
    }, {
        name: 4,
        code: '#333333'
    }, {
        name: 5,
        code: '#fefefe'
    }, {
        name: 6,
        code: '#87ceeb'
    }, {
        name: 7,
        code: '#20b2aa'
    }, {
        name: 8,
        code: '#90ee90'
    }, {
        name: 9,
        code: '#6b8e23'
    }, {
        name: 10,
        code: '#ffa500'
    }, {
        name: 11,
        code: '#a0522d'
    }, {
        name: 12,
        code: '#b22222'
    }, {
        name: 13,
        code: '#fa8072'
    }, {
        name: 14,
        code: '#dc143c'
    }, {
        name: 15,
        code: '#ffb6c1'
    }, {
        name: 16,
        code: '#da70d6'
    }, {
        name: 17,
        code: '#9370db'
    }
]